### ISSUE TITLE
Error: Could not find custom rule directory

### ISSUE THREAD

**Issue by joshforisha** [krzkaczor/standardts#2]
I'm receiving the following error when trying to run `standardts` after a fresh install.

```
node_modules/standardts/node_modules/tslint/lib/configuration.js:163
  throw new Error("Could not find custom rule directory: " + directory);

Error: Could not find custom rule directory: node_modules/standardts/node_modules/tslint-eslint-rules/dist/rules
```

Node v6.4.0, NPM v3.10.3

**Comment by krzkaczor** [comment]
Thanks for bug report. I will work on it this weekend.

**Comment by joshforisha** [comment]
Any progress on this?

**Comment by krzkaczor** [comment]
Sorry I haven't got time to work on this... THIS weekend :D I promise.

**Comment by krzkaczor** [comment]
Thanks for reporting - fixed it. Finding custom tslint rules was broken. I also fixed default glob patterns. 

Patched version was published on npm.

**Comment by letmaik** [comment]
I get the same error message with 0.1.4. This is because I switched to npm 3. There, all the dependency folders are flat and not nested, so `"rulesDirectory": "./node_modules/tslint-eslint-rules/dist/rules",` doesn't work anymore.
